# Site settings
title: Plog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Notes to self.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jhnklly
github_username:  jhnklly

# Build settings
#markdown: kramdown
markdown: redcarpet
# highlighter: rouge
highlighter: pygments

markdown_ext:  markdown,mkdown,mkdn,mkd,md

# http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis", "superscript"]

# Exploiting this config file to store a global object in a single place
# See 

exploits: 
  - date: 2015-04-27
    title: yourenottheonlyone
    tags: 
        hilo5
        l4
    prose:
        Not sure how this is going to work. Want
        <ol>
          <li> jekyll
          <li> Ideally, all posts in one file
          <li> Can misuse _config.yml
          <li> Can use html in config; but not _markdown_
          <li> editable online (prose.io)
          <li> anoni mouse
        </ol>
        But last two would require paid account? Instead, make this yourenottheonlyone account. Had always wanted to do a public anonymous blog anyway. (Screamsecrets)
